# Generated by Django 2.1 on 2018-08-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180815_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
