# Generated by Django 2.1 on 2018-08-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180815_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
